services:
  - type: web
    name: blog-backend
    runtime: python
    buildCommand: "../build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    rootDir: backend
    plan: free
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: null # Define on Render Panel (e.g.: https://backend.onrender.com)
      - key: CSRF_TRUSTED_ORIGINS
        value: null # Define on Render Panel (e.g.: https://backend.onrender.com)
      - key: CORS_ALLOWED_ORIGINS
        value: null # Define on Render Panel (e.g.: https://frontend.vercel.app)
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: blog-db
          property: connectionString

databases:
  - name: blog-db
    plan: free
