services:
  - type: web
    name: blog-backend
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
        value: null # Define on Render Panel, e.g. "django-insecure-abc123"
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: null # Define on Render Panel (e.g.: https://backend.onrender.com)
      - key: CORS_ALLOWED_ORIGINS
        value: null # Define on Render Panel (e.g.: https://frontend.vercel.app)
      - key: CSRF_TRUSTED_ORIGINS
        value: null # Define on Render Panel (e.g.: https://backend.onrender.com)
      - key: DATABASE_URL
        fromDatabase:
          name: blog-db
          property: connectionString

databases:
  - name: blog-db
    plan: free
